<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUGaYAYn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUGaYAYn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUGaYAYn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUGaYAYn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUGaYAYn\App_KernelDevDebugContainer([
    'container.build_hash' => 'UGaYAYn',
    'container.build_id' => 'ac868ff2',
    'container.build_time' => 1706994448,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUGaYAYn');
